url: http://spatialwomen.github.io/
baseurl: /

# Site settings
title: SpatialW
email: your-email@domain.com
description: An official website for SpatialW

# Team names, titles and social links
people:
- name: Jina Kim
  pic: 1
  position: General Chair, Webmaster
  social:
    - title: home
      url: https://jina-kim.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/jina-kim-5796a6134

- name: Min Namgung
  pic: 2
  position: General Chair
  social:
    - title: home
      url: https://minnamgung.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/minnamgung0115

- name: Leeje Jang
  pic: 3
  position: Recruitment Chair
  social:
    - title: home
      url: https://leejejang.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/leeje-jang/

- name: Sofia Kirsanova
  pic: 4
  position: Publicity Chair
  social:
    - title: home
      url: https://sofiakirsanova.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/sofia-kirsanova

- name:
  pic:
  position: Publicity Chair
  social:
    - title: home
      url:
    - title: linkedin
      url:

- name:
  pic:
  position: Sponsorship Chair
  social:
    - title: home
      url:
    - title: linkedin
      url:

members:
- name: Mariana Duarte
  affiliation: Univ. Libre de Bruxelles 

- name: Ketevan Gallagher
  affiliation: Thomas Jefferson High School for Science and Technology

- name: Jiawei Wei
  affiliation: Nanjing Institute of Geography & Limnology, Chinese Academy of Sciences

- name: Haoran Wang
  affiliation: National Univ. of Singapore

- name: Rowan Converse
  affiliation: Univ. of New Mexico

- name: Merve Polat Kayali
  affiliation: Univ. of Glasgow

- name: Betty Heller-Kaikov
  affiliation: Technical Univ. of Munich

- name: Haley Anne Schwartz
  affiliation: Univ. of Barcelona 

- name: Emma Von Hoene
  affiliation: George Mason Univ.

- name: Hrishikes Singh Yadav 
  affiliation: Manipal Institute of Technology 

- name: Blair Mirka
  affiliation: Univ. of New Mexico 

- name: Emily Hou
  affiliation: Wellesley College

- name: Kimberly Hsueh
  affiliation: Wellesley College

- name: Daniela Mariño Castro
  affiliation: Univ. of Zurich 

- name: Sidi Wu
  affiliation: ETH Zurich

- name: Iveel Tsogsuren
  affiliation: Google

- name: Annika Bonerath 
  affiliation: University of Bonn
  
- name: Hui Zhang
  affiliation: Univ. of Copenhagen

- name: Victoria Grace Ann
  affiliation: Singapore Management Univ.
  
- name: Qian Cao
  affiliation: Univ. of Georgia
  
- name: Theresa Chen
  affiliation: Univ. of Minnesota - Twin Cities

- name: Shang-Ling Hsu
  affiliation: Univ. of Southern California

- name: Sofia Kirsanova
  affiliation: Univ. of Minnesota - Twin Cities

- name: Ruochen Kong
  affiliation: Emory Univ.

- name: Areeg Mostafa
  affiliation: Univ. of Minnesota - Twin Cities

- name: Jiyoon Pyo
  affiliation: Univ. of Minnesota - Twin Cities

- name: Zhuocheng Shang
  affiliation: Univ. of Riverside

- name: Ana Uribe
  affiliation: Univ. of Minnesota - Twin Cities

- name: Jiaman Wu
  affiliation: Univ. of California, Berkeley

- name: Nemin Wu
  affiliation: Univ. of Georgia
  
- name: Dr. Fatme Hachem 
  affiliation: Univ. of Milan

- name: Dr. Yoohyung Joo
  affiliation: Yonsei University
  
- name: Dr. Yao Sun
  affiliation: Technical Univ. of Munich

- name: Prof. Negin Alisoltani 
  affiliation: Univ. Gustave Eiffel, Paris
  
- name: Prof. Taylor Anderson 
  affiliation: George Mason Univ.

- name: Prof. Christine Bassem
  affiliation: Wellesley College
  
- name: Prof. Flora Salim 
  affiliation: Univ. of New South Wales, Sydney
  
- name: Sophie Metzger
  affiliation: Apple

# Build settings
markdown: kramdown
permalink: pretty
