url: http://spatialwomen.github.io/
baseurl: /

# Site settings
title: SpatialW
email: your-email@domain.com
description: An official website for SpatialW

# Team names, titles and social links
people:
- name: Jina Kim
  pic: 1
  position: Organizer
  social:
    - title: home
      url: https://jina-kim.github.io/
    - title: twitter
      url: https://twitter.com/jina_kimmm/

- name: Min Namgung
  pic: 2
  position: Organizer
  social:
    - title: home
      url: https://minnamgung.github.io/
    - title: twitter
      url: #

# Build settings
markdown: kramdown
permalink: pretty