url: http://spatialwomen.github.io/
baseurl: /

# Site settings
title: SpatialW
email: your-email@domain.com
description: An official website for SpatialW

# Team names, titles and social links
people:
- name: Jina Kim
  pic: 1
  position: SpatialW Board of Directors | General Chair, Webmaster
  social:
    - title: home
      url: https://jina-kim.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/jina-kim-5796a6134

- name: Min Namgung
  pic: 2
  position: SpatialW Board of Directors | General Chair
  social:
    - title: home
      url: https://minnamgung.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/minnamgung0115

- name: Leeje Jang
  pic: 3
  position: SpatialW Board of Directors | Recruitment Chair
  social:
    - title: home
      url: https://leejejang.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/leeje-jang/

- name:
  pic:
  position: SpatialW Board of Directors | Sponsorship Chair
  social:
    - title: home
      url:
    - title: linkedin
      url:

- name: Sofia Kirsanova
  pic: 4
  position: SpatialW Board of Directors | Publicity Chair
  social:
    - title: home
      url: https://sofiakirsanova.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/sofia-kirsanova

- name:
  pic:
  position: SpatialW Board of Directors | Publicity Chair
  social:
    - title: home
      url:
    - title: linkedin
      url:

members:
- name: Member
- name: Member
- name: Member
- name: Member
- name: Member
- name: Member

# Build settings
markdown: kramdown
permalink: pretty