url: http://spatialwomen.github.io/
baseurl: /

# Site settings
title: SpatialW
email: your-email@domain.com
description: An official website for SpatialW

# Team names, titles and social links
people:
- name: Jina Kim
  pic: 1
  position: SpatialW Board of Directors | Web Master
  social:
    - title: home
      url: https://jina-kim.github.io/
    - title: twitter
      url: https://twitter.com/jina_kimmm/

- name: Min Namgung
  pic: 2
  position: SpatialW Board of Directors | Treasurer Chair
  social:
    - title: home
      url: https://minnamgung.github.io/
    - title: twitter
      url: https://twitter.com/min__namgung/

- name:
  pic:
  position: SpatialW Board of Directors | Sponsor Chair

- name:
  pic:
  position: SpatialW Board of Directors | Publicity Chair

# Build settings
markdown: kramdown
permalink: pretty
